"""add_medicines_table

Revision ID: 60db87e1774f
Revises: 96d1af9db61c
Create Date: 2026-06-18 22:43:15.884734

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '60db87e1774f'
down_revision: Union[str, Sequence[str], None] = '96d1af9db61c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('medicines',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('generic_name', sa.String(length=255), nullable=False),
    sa.Column('brand_name', sa.String(length=255), nullable=False),
    sa.Column('manufacturer', sa.String(length=255), nullable=True),
    sa.Column('strength', sa.String(length=100), nullable=False),
    sa.Column('dosage_form', sa.String(length=100), nullable=False),
    sa.Column('route', sa.String(length=100), nullable=False),
    sa.Column('drug_class', sa.String(length=255), nullable=True),
    sa.Column('requires_prescription', sa.Boolean(), nullable=False),
    sa.Column('contraindications', sa.Text(), nullable=True),
    sa.Column('side_effects', sa.Text(), nullable=True),
    sa.Column('drug_interactions', sa.Text(), nullable=True),
    sa.Column('pregnancy_category', sa.String(length=10), nullable=True),
    sa.Column('storage_information', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('medicines', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_medicines_drug_class'), ['drug_class'], unique=False)
        batch_op.create_index(batch_op.f('ix_medicines_generic_name'), ['generic_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_medicines_is_active'), ['is_active'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('medicines', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_medicines_is_active'))
        batch_op.drop_index(batch_op.f('ix_medicines_generic_name'))
        batch_op.drop_index(batch_op.f('ix_medicines_drug_class'))

    op.drop_table('medicines')
    # ### end Alembic commands ###
