"""add_prescription_items_table

Revision ID: 96d1af9db61c
Revises: dc156f9980cf
Create Date: 2026-06-18 21:35:59.103932

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '96d1af9db61c'
down_revision: Union[str, Sequence[str], None] = 'dc156f9980cf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prescription_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('prescription_id', sa.Integer(), nullable=False),
    sa.Column('medicine_name', sa.String(length=255), nullable=False),
    sa.Column('strength', sa.String(length=100), nullable=True),
    sa.Column('dosage', sa.String(length=100), nullable=True),
    sa.Column('frequency', sa.String(length=100), nullable=True),
    sa.Column('duration', sa.String(length=100), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('route', sa.String(length=100), nullable=True),
    sa.Column('instructions', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['prescription_id'], ['prescriptions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('prescription_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_prescription_items_prescription_id'), ['prescription_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prescription_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_prescription_items_prescription_id'))

    op.drop_table('prescription_items')
    # ### end Alembic commands ###
